### ISSUE TITLE
MenuButton "Is Selected" and Expand Arrow Rotation

### ISSUE THREAD

**Issue by andrewcartwright1** [beto-rodriguez/MaterialMenu#4]
Hey, Great work on this.

I've added it to my application, I do however have a request for a feature if you take them?
If a menu button is selected, it should have a unique color to show the user that this is the menu that they have selected.

If this menu button is a child of another menu button the parent should also be colored that unique color to show that this or a child of that menu button is selected.

If the menu button has children, when it is expanded the arrow should rotate (to basically suggest collapse menu) and vice versa

Many thanks

**Comment by beto-rodriguez** [comment]
Thanks, I will add alot of features to this menu, this will be included un next release too. Thanks again

**Comment by andrewcartwright1** [comment]
Awesome! Thank you, 
Looking forward to it!
