### ISSUE TITLE
Material menu throwing null referance exception

### ISSUE THREAD

**Issue by anirbandebroy** [beto-rodriguez/MaterialMenu#5]
![materialmenuerror](https://cloud.githubusercontent.com/assets/15009775/10812124/f1d5a806-7e38-11e5-8169-2cc385c5e10d.jpg)

The material menu is throwing error when button hover property is not set.Please check the code bellow which i am facing error

<materialMenu:SideMenu HorizontalAlignment="Left" x:Name="Menu"
                               MenuWidth="300"
                               Theme="Default"
                               State="Visible">
            materialMenu:SideMenu.Menu
                <ScrollViewer VerticalScrollBarVisibility="Hidden">
                    <StackPanel Orientation="Vertical">
                        <Border Background="#337AB5">
                            <Grid Margin="10">
                                <TextBox Height="150" BorderThickness="0" Background="Transparent"
                                    VerticalContentAlignment="Bottom" FontFamily="Calibri" FontSize="18"
                                    Foreground="WhiteSmoke" FontWeight="Bold">Welcome</TextBox>
                            </Grid>
                        </Border>
                        <materialMenu:MenuButton Text="Administration">/materialMenu:MenuButton
                        <materialMenu:MenuButton Text="Packing">/materialMenu:MenuButton
                        <materialMenu:MenuButton Text="Logistics">/materialMenu:MenuButton
                    </StackPanel>
                </ScrollViewer>
            /materialMenu:SideMenu.Menu
        /materialMenu:SideMenu

**Comment by anirbandebroy** [comment]
its even throwing error if you don't set the background is not set.
![materialmenu](https://cloud.githubusercontent.com/assets/15009775/10812218/eca47596-7e39-11e5-9430-e21635a297e6.jpg)

**Comment by beto-rodriguez** [comment]
Thank for reporting I will fix this in next realease

**Comment by anirbandebroy** [comment]
Hi Beto ca you provide me the jar file for this library?

**Comment by beto-rodriguez** [comment]
Hello, this library does not have a jar file, it is written in c#, this
control is only for test porpoises, maybe in a future I am fixing it.

Thanks.

2016-04-06 0:43 GMT-05:00 anirbandebroy notifications@github.com:

> Hi Beto ca you provide me the jar file for this library?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/beto-rodriguez/MaterialMenu/issues/5#issuecomment-206127807

## 

Alberto Rodríguez O.
