### ISSUE TITLE
Support for FontAwesome Images?

### ISSUE THREAD

**Issue by andrewcartwright1** [beto-rodriguez/MaterialMenu#6]
Hey,

Just another feature request, Support for: https://github.com/charri/Font-Awesome-WPF
I noticed that you can set an image, tried setting a fontawesome image however was not supported because it was an image source.

You can do this by using the following method

```
ImageAwesome.CreateImageSource(FontAwesomeIcon.Android)
```

My proposal was another property which could be used for setting a fontawesome image as the image?

**Comment by beto-rodriguez** [comment]
Thanks. I will make practically a full review of this Menu, to support this and all required templates I was thinking on implement a template as parameter, so you can decide how to display each element. Sadly I am not on this point yet. but I will add it as soon as possible. thaks for your request. I am using this menu for a production project and it works but I think it should be more flexible.
